Repository InvictoProjects/MarketPlace, pull requests merged in 2022-06, with the labels that each got.

#20 [MP-3] Update user related entities and services
  src/main/kotlin/com/invictoprojects/marketplace/persistence/model/Role.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/UserServiceImpl.kt
Labels: business logic

#21 [MP-4] Add category and product controllers and update related services
  src/main/kotlin/com/invictoprojects/marketplace/controller/CategoryController.kt
  src/main/kotlin/com/invictoprojects/marketplace/controller/ErrorController.kt
  src/main/kotlin/com/invictoprojects/marketplace/controller/ProductController.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/CategoryCreationDto.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/CategoryDto.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/MappingUtils.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/ProductCreationDto.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/ProductDto.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/model/Category.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/model/Product.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/repository/ProductRepository.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/CategoryService.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/ProductService.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/CategoryServiceImpl.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/ProductServiceImpl.kt
  src/main/resources/ValidationMessages.properties
  src/main/resources/application.properties
Labels: business logic

#22 [MP-9] Adding JWT support
  pom.xml
  src/main/kotlin/com/invictoprojects/marketplace/config/JwtProvider.kt
  src/main/kotlin/com/invictoprojects/marketplace/config/SecurityConfig.kt
  src/main/kotlin/com/invictoprojects/marketplace/controller/AuthController.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/AuthenticationResponse.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/LoginRequest.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/RefreshTokenRequest.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/RegisterRequest.kt
  src/main/kotlin/com/invictoprojects/marketplace/exception/InvalidCredentialsException.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/model/RefreshToken.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/model/User.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/repository/RefreshTokenRepository.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/AuthenticationService.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/RefreshTokenService.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/UserService.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/AuthenticationServiceImpl.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/RefreshTokenServiceImpl.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/UserDetailsServiceImpl.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/UserServiceImpl.kt
  src/main/resources/app.key
  src/main/resources/app.pub
  src/main/resources/application.properties
Labels: security, business logic

#28 [MP-14] Add recommendation emails
  pom.xml
  src/main/kotlin/com/invictoprojects/marketplace/MarketPlaceApplication.kt
  src/main/kotlin/com/invictoprojects/marketplace/controller/UserController.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/MappingUtils.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/UserDto.kt
  src/main/kotlin/com/invictoprojects/marketplace/jobs/EmailEngine.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/model/User.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/repository/UserRepository.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/EmailService.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/RecommendationService.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/UserService.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/EmailServiceImpl.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/ProductServiceImpl.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/RecommendationServiceImpl.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/UserServiceImpl.kt
  src/main/resources/application.properties
  src/main/resources/templates/recommendation_email.ftlh
Labels: dependencies, build infrastructure, business logic

#29 [MP-15] Add Controller methods for Review entity
  src/main/kotlin/com/invictoprojects/marketplace/controller/ProductController.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/MappingUtils.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/ProductDto.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/ReviewCreationDto.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/ReviewDto.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/model/Product.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/model/Review.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/ProductService.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/ReviewService.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/UserService.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/ProductServiceImpl.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/ReviewServiceImpl.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/UserServiceImpl.kt
  src/main/resources/ValidationMessages.properties
Labels: business logic

#31 [MP-11] Adding Swagger config
  pom.xml
  src/main/kotlin/com/invictoprojects/marketplace/config/SwaggerConfig.kt
  src/main/kotlin/com/invictoprojects/marketplace/config/WebConfig.kt
Labels: dependencies, testing

#39 [MP-18] Add CI with Maven GitHub workflow
  .github/workflows/maven.yml
  pom.xml
  src/main/kotlin/com/invictoprojects/marketplace/persistence/model/Order.kt
  src/test/kotlin/com/invictoprojects/marketplace/MarketPlaceApplicationTests.kt
Labels: ci

#35 [MP-12] Update application.properties
  src/main/resources/application.properties
Labels: build infrastructure

#37 [MP-20] Add search for products
  src/main/kotlin/com/invictoprojects/marketplace/controller/ProductController.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/repository/ProductRepository.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/ProductService.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/ProductServiceImpl.kt
Labels: business logic

#40 [MP-6] Update order related entities and services
  src/main/kotlin/com/invictoprojects/marketplace/controller/OrderController.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/OrderCreationDto.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/OrderDetailDto.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/OrderDto.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/OrderService.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/OrderServiceImpl.kt
  src/main/resources/ValidationMessages.properties
Labels: business logic

#42 [MP-21] Add unit tests for Review Service
  pom.xml
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/ProductServiceImpl.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/ReviewServiceImpl.kt
  src/test/kotlin/com/invictoprojects/marketplace/service/impl/ProductServiceImplTest.kt
  src/test/kotlin/com/invictoprojects/marketplace/service/impl/ReviewServiceImplTest.kt
Labels: testing

#43 [MP-17] Add Exception Handler
  src/main/kotlin/com/invictoprojects/marketplace/controller/AuthController.kt
  src/main/kotlin/com/invictoprojects/marketplace/controller/CategoryController.kt
  src/main/kotlin/com/invictoprojects/marketplace/controller/ErrorController.kt
  src/main/kotlin/com/invictoprojects/marketplace/controller/ExceptionHandler.kt
  src/main/kotlin/com/invictoprojects/marketplace/controller/OrderController.kt
  src/main/kotlin/com/invictoprojects/marketplace/controller/ProductController.kt
  src/main/kotlin/com/invictoprojects/marketplace/controller/UserController.kt
  src/main/kotlin/com/invictoprojects/marketplace/exception/ErrorMessage.kt
Labels: business logic

#41 Adding tests for authentication service
  src/test/kotlin/com/invictoprojects/marketplace/service/impl/AuthenticationServiceTest.kt
Labels: testing

#44 [MP-13] Add Linter and Refactor code to match linter rules
  .github/workflows/maven.yml
  pom.xml
  src/main/kotlin/com/invictoprojects/marketplace/config/SwaggerConfig.kt
  src/main/kotlin/com/invictoprojects/marketplace/config/WebConfig.kt
  src/main/kotlin/com/invictoprojects/marketplace/controller/AuthController.kt
  src/main/kotlin/com/invictoprojects/marketplace/controller/CategoryController.kt
  src/main/kotlin/com/invictoprojects/marketplace/controller/ErrorController.kt
  src/main/kotlin/com/invictoprojects/marketplace/controller/ExceptionHandler.kt
  src/main/kotlin/com/invictoprojects/marketplace/controller/OrderController.kt
  src/main/kotlin/com/invictoprojects/marketplace/controller/ProductController.kt
  src/main/kotlin/com/invictoprojects/marketplace/controller/UserController.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/CategoryCreationDto.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/MappingUtils.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/OrderCreationDto.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/OrderDetailDto.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/OrderDto.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/OrderStatusDto.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/ProductDto.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/ReviewDto.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/UserDto.kt
  src/main/kotlin/com/invictoprojects/marketplace/jobs/EmailEngine.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/model/Category.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/model/Order.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/model/OrderProduct.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/model/OrderProductKey.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/model/Product.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/model/RefreshToken.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/model/Review.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/model/ReviewId.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/model/User.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/repository/CategoryRepository.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/repository/ProductRepository.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/repository/RefreshTokenRepository.kt
  src/main/kotlin/com/invictoprojects/marketplace/persistence/repository/UserRepository.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/CategoryService.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/EmailService.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/OrderService.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/RecommendationService.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/UserService.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/AuthenticationServiceImpl.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/CategoryServiceImpl.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/EmailServiceImpl.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/OrderServiceImpl.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/ProductServiceImpl.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/RecommendationServiceImpl.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/ReviewServiceImpl.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/UserDetailsServiceImpl.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/UserServiceImpl.kt
  src/test/kotlin/com/invictoprojects/marketplace/service/impl/ProductServiceImplTest.kt
  src/test/kotlin/com/invictoprojects/marketplace/service/impl/ReviewServiceImplTest.kt
Labels: ci, dependencies

#45 [MP-6] Add order related entities and services
  src/main/kotlin/com/invictoprojects/marketplace/controller/ExceptionHandler.kt
  src/main/kotlin/com/invictoprojects/marketplace/controller/OrderController.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/OrderServiceImpl.kt
  src/test/kotlin/com/invictoprojects/marketplace/service/impl/AuthenticationServiceTest.kt
Labels: business logic

#47 [MP-21] Add unit tests for UserService
  src/test/kotlin/com/invictoprojects/marketplace/service/impl/UserServiceImplTest.kt
Labels: testing

#52 [MP-23] Update README.md
  README.md
Labels: documentation

#51 [MP-21] Add unit tests for categories and products
  pom.xml
  src/main/kotlin/com/invictoprojects/marketplace/config/JwtProvider.kt
  src/main/kotlin/com/invictoprojects/marketplace/controller/ErrorController.kt
  src/main/kotlin/com/invictoprojects/marketplace/dto/MappingUtils.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/CategoryService.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/ProductService.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/CategoryServiceImpl.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/ProductServiceImpl.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/RefreshTokenServiceImpl.kt
  src/main/kotlin/com/invictoprojects/marketplace/service/impl/UserServiceImpl.kt
  src/main/resources/ValidationMessages.properties
  src/test/kotlin/com/invictoprojects/marketplace/service/impl/CategoryServiceImplTest.kt
  src/test/kotlin/com/invictoprojects/marketplace/service/impl/ProductServiceImplTest.kt
Labels: testing
